// Explicit answer AND distractor pools keep broad clues unambiguous.
// A distractor is reviewed for this clue, rather than inferred from a missing tag.
const clue = (id, answers, distractors, ru, he, en) => ({
  id,
  answers: answers.split(" "),
  distractors: distractors.split(" "),
  prompts: { ru, he, en },
});
export const clues = [
  clue(
    "woof",
    "dog",
    "cat cow duck frog bird",
    "Кто говорит «гав-гав»?",
    "מִי אוֹמֵר הַב הַב?",
    "Who says woof?",
  ),
  clue(
    "meow",
    "cat",
    "dog cow duck horse sheep",
    "Кто говорит «мяу»?",
    "מִי אוֹמֵר מְיָאוּ?",
    "Who says meow?",
  ),
  clue(
    "moo",
    "cow",
    "dog cat duck frog lion",
    "Кто говорит «му»?",
    "מִי אוֹמֵר מוּ?",
    "Who says moo?",
  ),
  clue(
    "quack",
    "duck",
    "dog cat cow horse sheep",
    "Кто говорит «кря-кря»?",
    "מִי אוֹמֵר גַּע גַּע?",
    "Who says quack?",
  ),
  clue(
    "baa",
    "sheep",
    "dog cat duck frog lion",
    "Кто говорит «бе-е»?",
    "מִי אוֹמֵר מֶה?",
    "Who says baa?",
  ),
  clue(
    "rooster",
    "rooster",
    "dog cat cow duck sheep",
    "Кто кричит «кукареку»?",
    "מִי קוֹרֵא קוּקוּרִיקוּ?",
    "Who says cock-a-doodle-doo?",
  ),
  clue(
    "oink",
    "pig",
    "dog cat cow duck horse",
    "Кто хрюкает?",
    "מִי אוֹמֵר חְרוֹם חְרוֹם?",
    "Who says oink?",
  ),
  clue(
    "neigh",
    "horse",
    "dog cat sheep duck frog",
    "Кто говорит «и-го-го»?",
    "מִי צוֹהֵל?",
    "Who says neigh?",
  ),
  clue(
    "trunk",
    "elephant",
    "lion rabbit giraffe monkey bear",
    "У кого длинный хобот?",
    "לְמִי יֵשׁ חֵדֶק אָרֹךְ?",
    "Who has a long trunk?",
  ),
  clue(
    "neck",
    "giraffe",
    "lion dog pig rabbit turtle",
    "У кого очень длинная шея?",
    "לְמִי יֵשׁ צַוָּאר אָרֹךְ מְאוֹד?",
    "Who has a very long neck?",
  ),
  clue(
    "mane",
    "lion",
    "elephant rabbit frog turtle sheep",
    "У кого большая грива вокруг морды?",
    "לְמִי יֵשׁ רַעֲמָה סְבִיב הַפָּנִים?",
    "Who has a big mane around their face?",
  ),
  clue(
    "ears",
    "rabbit",
    "frog fish turtle bird penguin",
    "У кого длинные уши?",
    "לְמִי יֵשׁ אָזְנַיִם אֲרֻכּוֹת?",
    "Who has long ears?",
  ),
  clue(
    "shell",
    "turtle",
    "dog cat horse pig lion",
    "Кто носит панцирь на спине?",
    "לְמִי יֵשׁ שִׁרְיוֹן עַל הַגַּב?",
    "Who carries a shell on their back?",
  ),
  clue(
    "snail",
    "snail",
    "lion dog cat elephant giraffe",
    "Кто ползёт с домиком на спине?",
    "מִי זוֹחֵל עִם בַּיִת עַל הַגַּב?",
    "Who crawls with a little house on their back?",
  ),
  clue(
    "butterfly",
    "butterfly",
    "dog cat turtle snail pig",
    "Кто летает с большими цветными крыльями?",
    "מִי עָף עִם כְּנָפַיִם צִבְעוֹנִיּוֹת?",
    "Who flies with colorful wings?",
  ),
  clue(
    "honey",
    "bee",
    "butterfly bird duck frog fish",
    "Кто делает мёд?",
    "מִי מְכִינָה דְּבַשׁ?",
    "Who makes honey?",
  ),
  clue(
    "water",
    "fish",
    "cat dog lion giraffe sheep",
    "Кто живёт под водой?",
    "מִי חַי מִתַּחַת לַמַּיִם?",
    "Who lives underwater?",
  ),
  clue(
    "sweet",
    "candy cake chocolate icecream",
    "chair key shoe scissors bus pencil",
    "Что сладкое?",
    "מָה מָתוֹק?",
    "What is sweet?",
  ),
  clue(
    "sour",
    "lemon",
    "bread cheese egg milk sausage",
    "Что кислое?",
    "מָה חָמוּץ?",
    "What tastes sour?",
  ),
  clue(
    "red",
    "apple tomato strawberry",
    "banana lemon cucumber milk cloud cheese",
    "Что красное на картинке?",
    "מָה אָדֹם בַּתְּמוּנָה?",
    "What is red in the picture?",
  ),
  clue(
    "yellow",
    "banana lemon cheese",
    "grapes cucumber strawberry tomato milk",
    "Что жёлтое на картинке?",
    "מָה צָהֹב בַּתְּמוּנָה?",
    "What is yellow in the picture?",
  ),
  clue(
    "green",
    "cucumber leaf",
    "banana lemon strawberry tomato cheese",
    "Что зелёное на картинке?",
    "מָה יָרֹק בַּתְּמוּנָה?",
    "What is green in the picture?",
  ),
  clue(
    "fruit",
    "apple pear banana orange grapes watermelon",
    "chair key shoe drum bus pencil",
    "Где фрукт?",
    "אֵיפֹה הַפְּרִי?",
    "Which one is a fruit?",
  ),
  clue(
    "drink",
    "juice milk",
    "bread cheese carrot egg pizza",
    "Что можно пить?",
    "מָה אֶפְשָׁר לִשְׁתּוֹת?",
    "What can you drink?",
  ),
  clue(
    "cold",
    "icecream",
    "bread cheese sausage carrot banana",
    "Что холодное и тает?",
    "מָה קַר וְנָמֵס?",
    "What is cold and melts?",
  ),
  clue(
    "carrot",
    "carrot",
    "banana grapes apple pear watermelon",
    "Какой овощ любит кролик?",
    "אֵיזֶה יָרָק הָאַרְנָב אוֹהֵב?",
    "Which vegetable does a rabbit like?",
  ),
  clue(
    "read",
    "book",
    "ball shoe spoon drum hat chair",
    "Что можно читать?",
    "מָה אֶפְשָׁר לִקְרֹא?",
    "What can you read?",
  ),
  clue(
    "time",
    "clock",
    "book chair ball cup hat spoon",
    "Что показывает время?",
    "מָה מַרְאֶה אֶת הַשָּׁעָה?",
    "What tells the time?",
  ),
  clue(
    "rain",
    "umbrella",
    "spoon pencil ball key drum chair",
    "Что защищает от дождя?",
    "מָה מֵגֵן מִפְּנֵי הַגֶּשֶׁם?",
    "What keeps the rain off you?",
  ),
  clue(
    "unlock",
    "key",
    "spoon pencil brush hat ball drum",
    "Чем открывают замок?",
    "בְּמָה פּוֹתְחִים מַנְעוּל?",
    "What opens a lock?",
  ),
  clue(
    "sleep",
    "bed",
    "bicycle spoon clock guitar umbrella",
    "Где мы спим?",
    "אֵיפֹה אֲנַחְנוּ יְשֵׁנִים?",
    "Where do we sleep?",
  ),
  clue(
    "sit",
    "chair",
    "pencil cup key spoon clock brush",
    "На чём мы сидим?",
    "עַל מָה אֲנַחְנוּ יוֹשְׁבִים?",
    "What do we sit on?",
  ),
  clue(
    "soup",
    "spoon",
    "pencil brush key scissors sock",
    "Чем мы едим суп?",
    "בְּמָה אוֹכְלִים מָרָק?",
    "What do we use to eat soup?",
  ),
  clue(
    "teeth",
    "brush",
    "pencil key spoon scissors guitar",
    "Чем мы чистим зубы?",
    "בְּמָה מְצַחְצְחִים שִׁנַּיִם?",
    "What do we use to brush our teeth?",
  ),
  clue(
    "draw",
    "pencil",
    "spoon brush key sock cup",
    "Чем мы рисуем на бумаге?",
    "בְּמָה מְצַיְּרִים עַל נְיָר?",
    "What do we use to draw on paper?",
  ),
  clue(
    "cut",
    "scissors",
    "pencil key spoon cup clock",
    "Чем мы режем бумагу?",
    "בְּמָה גּוֹזְרִים נְיָר?",
    "What do we use to cut paper?",
  ),
  clue(
    "head",
    "hat",
    "sock shoe shirt mitten spoon",
    "Что надевают на голову?",
    "מָה חוֹבְשִׁים עַל הָרֹאשׁ?",
    "What do we wear on our head?",
  ),
  clue(
    "hands",
    "mitten",
    "hat sock shoe shirt spoon",
    "Что согревает руки?",
    "מָה מְחַמֵּם אֶת הַיָּדַיִם?",
    "What keeps our hands warm?",
  ),
  clue(
    "feet",
    "shoe sock",
    "hat shirt mitten clock pencil",
    "Что надевают на ноги?",
    "מָה לוֹבְשִׁים עַל כַּפּוֹת הָרַגְלַיִם?",
    "What do we wear on our feet?",
  ),
  clue(
    "rails",
    "train",
    "car bus plane bicycle boat",
    "Что едет по рельсам?",
    "מָה נוֹסֵעַ עַל מְסִלָּה?",
    "What travels on rails?",
  ),
  clue(
    "fly",
    "plane",
    "car bus train bicycle boat",
    "На чём можно летать в небе?",
    "בְּמָה אֶפְשָׁר לָטוּס בַּשָּׁמַיִם?",
    "What can you fly in the sky?",
  ),
  clue(
    "sail",
    "boat",
    "car bus train bicycle plane",
    "На чём можно плыть по воде?",
    "בְּמָה אֶפְשָׁר לָשׁוּט עַל הַמַּיִם?",
    "What can you sail on the water?",
  ),
  clue(
    "pedals",
    "bicycle",
    "car bus train plane boat",
    "У чего два колеса и педали?",
    "לְמָה יֵשׁ שְׁנֵי גַּלְגַּלִּים וּדְוָשׁוֹת?",
    "What has two wheels and pedals?",
  ),
  clue(
    "space",
    "rocket",
    "car bus boat train bicycle",
    "На чём летают в космос?",
    "בְּמָה טָסִים לֶחָלָל?",
    "What flies into space?",
  ),
  clue(
    "kick",
    "ball",
    "book clock cup spoon hat",
    "Что можно пинать в игре?",
    "בְּמָה בּוֹעֲטִים בַּמִּשְׂחָק?",
    "What can you kick in a game?",
  ),
  clue(
    "strings",
    "guitar",
    "drum ball book clock chair",
    "У какого инструмента есть струны?",
    "לְאֵיזֶה כְּלִי נְגִינָה יֵשׁ מֵיתָרִים?",
    "Which musical instrument has strings?",
  ),
  clue(
    "beat",
    "drum",
    "guitar ball book clock chair",
    "По чему стучат палочками, чтобы играть музыку?",
    "עַל מָה מַכִּים בְּמַקְלוֹת כְּדֵי לְנַגֵּן?",
    "What do we beat with sticks to make music?",
  ),
  clue(
    "snow",
    "snowman",
    "tree flower mushroom leaf house",
    "Кого мы лепим из снега?",
    "מַה בּוֹנִים מִשֶּׁלֶג?",
    "What do we build from snow?",
  ),
  clue(
    "rainbow",
    "rainbow",
    "sun moon cloud star snowman",
    "Что появляется после дождя и имеет много цветов?",
    "מָה מוֹפִיעַ אַחֲרֵי הַגֶּשֶׁם וְיֵשׁ לוֹ הַרְבֵּה צְבָעִים?",
    "What appears after rain with many colors?",
  ),
  clue(
    "sun",
    "sun",
    "moon cloud star snowman leaf",
    "Что светит и греет нас днём?",
    "מָה מֵאִיר וּמְחַמֵּם אוֹתָנוּ בַּיּוֹם?",
    "What shines and warms us during the day?",
  ),
];
