import * as chinese from "../locales/zh.js";
import * as japanese from "../locales/ja.js";
// Each locale is curated independently. `initial` is the letter, pinyin unit or kana taught.
const item = (id, ru, he, en, initials, facts = []) => ({
  id,
  art: id,
  facts,
  words: {
    zh: {
      display: chinese.vocabulary[id][0],
      speech: chinese.vocabulary[id][0],
      reading: chinese.vocabulary[id][1],
      initial: chinese.vocabulary[id][1].normalize("NFD").replace(/\p{M}/gu, "").match(/^(zh|ch|sh|[a-z])/u)[0],
    },
    ja: {
      display: japanese.vocabulary[id][0],
      speech: japanese.vocabulary[id][1],
      initial: [...japanese.vocabulary[id][0]][0],
    },
    ru: { display: ru, speech: ru, initial: initials[0] },
    he: { display: he, speech: he, initial: initials[1] },
    en: { display: en, speech: en, initial: initials[2] },
  },
});
export const concepts = [
  item("dog", "собака", "כֶּלֶב", "dog", ["С", "כ", "D"], ["woof", "animal"]),
  item("cat", "кот", "חָתוּל", "cat", ["К", "ח", "C"], ["meow", "animal"]),
  item("juice", "сок", "מִיץ", "juice", ["С", "מ", "J"], ["drink"]),
  item(
    "sausage",
    "сосиска",
    "נַקְנִיקִיָּה",
    "sausage",
    ["С", "נ", "S"],
    ["food"],
  ),
  item("sun", "солнце", "שֶׁמֶשׁ", "sun", ["С", "ש", "S"], ["sky"]),
  item("house", "дом", "בַּיִת", "house", ["Д", "ב", "H"], ["building"]),
  item("banana", "банан", "בָּנָנָה", "banana", ["Б", "ב", "B"], ["fruit"]),
  item("balloon", "шарик", "בַּלּוֹן", "balloon", ["Ш", "ב", "B"], ["toy"]),
  item("milk", "молоко", "חָלָב", "milk", ["М", "ח", "M"], ["drink"]),
  item("window", "окно", "חַלּוֹן", "window", ["О", "ח", "W"], ["building"]),
  item("clock", "часы", "שָׁעוֹן", "clock", ["Ч", "ש", "C"], ["time"]),
  item(
    "chocolate",
    "шоколад",
    "שׁוֹקוֹלָד",
    "chocolate",
    ["Ш", "ש", "C"],
    ["sweet"],
  ),
  item("cow", "корова", "פָּרָה", "cow", ["К", "פ", "C"], ["moo", "animal"]),
  item("book", "книга", "סֵפֶר", "book", ["К", "ס", "B"], ["reading"]),
  item("candy", "конфета", "מַמְתָּק", "candy", ["К", "מ", "C"], ["sweet"]),
  item("cake", "торт", "עוּגָה", "cake", ["Т", "ע", "C"], ["sweet"]),
  item("car", "машина", "מְכוֹנִית", "car", ["М", "מ", "C"], ["vehicle"]),
  item(
    "duck",
    "утка",
    "בַּרְוָז",
    "duck",
    ["У", "ב", "D"],
    ["quack", "animal"],
  ),
  item(
    "apple",
    "яблоко",
    "תַּפּוּחַ",
    "apple",
    ["Я", "ת", "A"],
    ["red", "fruit"],
  ),
  item("fish", "рыба", "דָּג", "fish", ["Р", "ד", "F"], ["animal", "water"]),
  item("tree", "дерево", "עֵץ", "tree", ["Д", "ע", "T"], ["plant"]),
  item("flower", "цветок", "פֶּרַח", "flower", ["Ц", "פ", "F"], ["plant"]),
  item("ball", "мяч", "כַּדּוּר", "ball", ["М", "כ", "B"], ["toy"]),
  item("star", "звезда", "כּוֹכָב", "star", ["З", "כ", "S"], ["sky"]),
  item("shoe", "ботинок", "נַעַל", "shoe", ["Б", "נ", "S"], ["clothing"]),
  item("rabbit", "кролик", "אַרְנָב", "rabbit", ["К", "א", "R"]),
  item("bear", "медведь", "דֹּב", "bear", ["М", "ד", "B"]),
  item("lion", "лев", "אַרְיֵה", "lion", ["Л", "א", "L"]),
  item("elephant", "слон", "פִּיל", "elephant", ["С", "פ", "E"]),
  item("giraffe", "жираф", "גִּ׳ירָפָה", "giraffe", ["Ж", "ג", "G"]),
  item("monkey", "обезьяна", "קוֹף", "monkey", ["О", "ק", "M"]),
  item("horse", "лошадь", "סוּס", "horse", ["Л", "ס", "H"]),
  item("sheep", "овца", "כֶּבֶשׂ", "sheep", ["О", "כ", "S"]),
  item("pig", "свинья", "חֲזִיר", "pig", ["С", "ח", "P"]),
  item("mouse", "мышь", "עַכְבָּר", "mouse", ["М", "ע", "M"]),
  item("frog", "лягушка", "צְפַרְדֵּעַ", "frog", ["Л", "צ", "F"]),
  item("turtle", "черепаха", "צָב", "turtle", ["Ч", "צ", "T"]),
  item("butterfly", "бабочка", "פַּרְפַּר", "butterfly", ["Б", "פ", "B"]),
  item("bee", "пчела", "דְּבוֹרָה", "bee", ["П", "ד", "B"]),
  item("snail", "улитка", "חִלָּזוֹן", "snail", ["У", "ח", "S"]),
  item("bird", "птица", "צִפּוֹר", "bird", ["П", "צ", "B"]),
  item("rooster", "петух", "תַּרְנְגוֹל", "rooster", ["П", "ת", "R"]),
  item("penguin", "пингвин", "פִּינְגְּוִין", "penguin", ["П", "פ", "P"]),
  item("pear", "груша", "אַגָּס", "pear", ["Г", "א", "P"]),
  item("orange", "апельсин", "תַּפּוּז", "orange", ["А", "ת", "O"]),
  item("lemon", "лимон", "לִימוֹן", "lemon", ["Л", "ל", "L"]),
  item("strawberry", "клубника", "תּוּת", "strawberry", ["К", "ת", "S"]),
  item("grapes", "виноград", "עֲנָבִים", "grapes", ["В", "ע", "G"]),
  item("watermelon", "арбуз", "אֲבַטִּיחַ", "watermelon", ["А", "א", "W"]),
  item("carrot", "морковь", "גֶּזֶר", "carrot", ["М", "ג", "C"]),
  item("tomato", "помидор", "עַגְבָנִיָּה", "tomato", ["П", "ע", "T"]),
  item("cucumber", "огурец", "מְלָפְפוֹן", "cucumber", ["О", "מ", "C"]),
  item("bread", "хлеб", "לֶחֶם", "bread", ["Х", "ל", "B"]),
  item("cheese", "сыр", "גְּבִינָה", "cheese", ["С", "ג", "C"]),
  item("egg", "яйцо", "בֵּיצָה", "egg", ["Я", "ב", "E"]),
  item("icecream", "мороженое", "גְּלִידָה", "ice cream", ["М", "ג", "I"]),
  item("pizza", "пицца", "פִּיצָה", "pizza", ["П", "פ", "P"]),
  item("bus", "автобус", "אוֹטוֹבּוּס", "bus", ["А", "א", "B"]),
  item("train", "поезд", "רַכֶּבֶת", "train", ["П", "ר", "T"]),
  item("plane", "самолёт", "מָטוֹס", "plane", ["С", "מ", "P"]),
  item("boat", "лодка", "סִירָה", "boat", ["Л", "ס", "B"]),
  item("bicycle", "велосипед", "אוֹפַנַּיִם", "bicycle", ["В", "א", "B"]),
  item("rocket", "ракета", "טִיל", "rocket", ["Р", "ט", "R"]),
  item("umbrella", "зонт", "מִטְרִיָּה", "umbrella", ["З", "מ", "U"]),
  item("key", "ключ", "מַפְתֵּחַ", "key", ["К", "מ", "K"]),
  item("chair", "стул", "כִּסֵּא", "chair", ["С", "כ", "C"]),
  item("bed", "кровать", "מִטָּה", "bed", ["К", "מ", "B"]),
  item("cup", "чашка", "סֵפֶל", "cup", ["Ч", "ס", "C"]),
  item("spoon", "ложка", "כַּף", "spoon", ["Л", "כ", "S"]),
  item("brush", "зубная щётка", "מִבְרֶשֶׁת שִׁנַּיִם", "toothbrush", [
    "З",
    "מ",
    "T",
  ]),
  item("pencil", "карандаш", "עִפָּרוֹן", "pencil", ["К", "ע", "P"]),
  item("scissors", "ножницы", "מִסְפָּרַיִם", "scissors", ["Н", "מ", "S"]),
  item("hat", "шапка", "כּוֹבַע", "hat", ["Ш", "כ", "H"]),
  item("shirt", "рубашка", "חֻלְצָה", "shirt", ["Р", "ח", "S"]),
  item("sock", "носок", "גֶּרֶב", "sock", ["Н", "ג", "S"]),
  item("mitten", "варежка", "כְּפָפָה", "mitten", ["В", "כ", "M"]),
  item("drum", "барабан", "תֹּף", "drum", ["Б", "ת", "D"]),
  item("guitar", "гитара", "גִּיטָרָה", "guitar", ["Г", "ג", "G"]),
  item("kite", "воздушный змей", "עֲפִיפוֹן", "kite", ["В", "ע", "K"]),
  item("moon", "луна", "יָרֵחַ", "moon", ["Л", "י", "M"]),
  item("cloud", "облако", "עָנָן", "cloud", ["О", "ע", "C"]),
  item("rainbow", "радуга", "קֶשֶׁת", "rainbow", ["Р", "ק", "R"]),
  item("snowman", "снеговик", "אִישׁ שֶׁלֶג", "snowman", ["С", "א", "S"]),
  item("leaf", "лист", "עָלֶה", "leaf", ["Л", "ע", "L"]),
  item("mushroom", "гриб", "פִּטְרִיָּה", "mushroom", ["Г", "פ", "M"]),
  item("shell", "ракушка", "צְדָפָה", "shell", ["Р", "צ", "S"]),
];
export const byId = Object.fromEntries(
  concepts.map((concept) => [concept.id, concept]),
);
export const alphabets = {
  zh: chinese.alphabet,
  ja: japanese.alphabet,
  ru: [..."АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ"],
  he: [..."אבגדהוזחטיכלמנסעפצקרשת"],
  en: [..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"],
};
export const earlyLetters = {
  zh: chinese.early,
  ja: japanese.early,
  ru: ["А", "Б", "В", "Д", "К", "М", "О", "С", "Т"],
  he: ["א", "ב", "ג", "ד", "ה", "ו", "ח", "כ", "מ", "ש"],
  en: ["A", "B", "C", "D", "E", "F", "H", "M", "S"],
};
export const earlyRuns = {
  zh: chinese.rows.slice(0, 4).map((row) => row.slice(0, 3)),
  ja: japanese.rows.slice(0, 7).map((row) => row.slice(0, 3)),
  ru: [
    ["А", "Б", "В"],
    ["Г", "Д", "Е"],
    ["И", "Й", "К"],
    ["К", "Л", "М"],
    ["М", "Н", "О"],
    ["О", "П", "Р"],
    ["С", "Т", "У"],
  ],
  he: [
    ["א", "ב", "ג"],
    ["ד", "ה", "ו"],
    ["ז", "ח", "ט"],
    ["י", "כ", "ל"],
    ["מ", "נ", "ס"],
    ["ע", "פ", "צ"],
    ["ק", "ר", "ש"],
  ],
  en: [
    ["A", "B", "C"],
    ["D", "E", "F"],
    ["G", "H", "I"],
    ["J", "K", "L"],
    ["M", "N", "O"],
    ["P", "Q", "R"],
    ["S", "T", "U"],
  ],
};
export function word(concept, locale) {
  return concept.words[locale];
}
// These writing systems use teaching rows rather than an English alphabet order.
export const literacyRows = { zh: chinese.rows, ja: japanese.rows };
export function groups(locale) {
  const result = new Map();
  for (const concept of concepts) {
    const initial = word(concept, locale).initial;
    result.set(initial, [...(result.get(initial) || []), concept]);
  }
  return [...result].filter(([, items]) => items.length >= 3);
}
