"""Build optional-dependency audio assets: pip install edge-tts==7.2.8; python scripts/generate-audio.py.
Authored game text only. No runtime speech service, API key, or external request.
Existing hashed clips are reused. Commit assets and manifest together.
"""
import asyncio, hashlib, json, pathlib, subprocess
import edge_tts
ROOT=pathlib.Path(__file__).resolve().parents[1]
VOICES={'ru':'ru-RU-SvetlanaNeural','he':'he-IL-HilaNeural','en':'en-US-AriaNeural'}
catalog=json.loads(subprocess.check_output(['node','scripts/audio-catalog.js'],cwd=ROOT))
manifest={locale:{} for locale in catalog}
semaphore=asyncio.Semaphore(4)
completed=0
async def generate(locale,text):
 global completed
 digest=hashlib.sha256((locale+'\n'+text).encode()).hexdigest()[:16]
 relative=f'audio/{locale}/{digest}.mp3'
 path=ROOT/relative
 path.parent.mkdir(parents=True,exist_ok=True)
 manifest[locale][text]=relative
 async with semaphore:
  if not path.exists() or path.stat().st_size<1000:
   for attempt in range(5):
    try:
     tmp=path.with_suffix('.tmp')
     await edge_tts.Communicate(text,VOICES[locale],rate='-12%').save(str(tmp))
     if tmp.stat().st_size<1000: raise ValueError('Empty audio')
     tmp.replace(path)
     break
    except Exception:
     if attempt==4: raise
     await asyncio.sleep(2**attempt)
  completed+=1
  if completed%30==0: print(f'{completed} clips ready',flush=True)
async def main():
 await asyncio.gather(*(generate(locale,text) for locale,texts in catalog.items() for text in texts))
 (ROOT/'src/core/audio-manifest.js').write_text('// Generated by scripts/generate-audio.py.\nexport const audioManifest = '+json.dumps(manifest,ensure_ascii=False,indent=2)+';\n')
 print(f'Done: {completed} clips; {sum(p.stat().st_size for p in (ROOT/"audio").rglob("*.mp3"))/1024/1024:.1f} MiB',flush=True)
asyncio.run(main())
